"""
Comprehensive French Sentiment Lexicon.
Contains weighted sentiment words, negations, and intensifiers.
"""

# Sentiment dictionary: word -> score (-4.0 to +4.0)
FRENCH_LEXICON = {
    # POSITIVE (1.0 to 4.0)
    "excellent": 3.5,
    "parfait": 3.5,
    "génial": 3.0,
    "super": 2.5,
    "superbe": 3.0,
    "magnifique": 3.0,
    "fantastique": 3.0,
    "formidable": 3.0,
    "merveilleux": 3.0,
    "extraordinaire": 3.0,
    "incroyable": 2.5,
    "top": 2.0,
    "bien": 1.5,
    "bon": 1.5,
    "agréable": 2.0,
    "satisfait": 2.0,
    "content": 2.0,
    "heureux": 2.0,
    "ravi": 2.5,
    "adore": 3.0,
    "aime": 2.0,
    "recommande": 2.5,
    "efficace": 2.0,
    "rapide": 1.5,
    "utile": 1.5,
    "pratique": 1.5,
    "qualité": 2.0,
    "fiable": 2.0,
    "correct": 0.5,
    "honnête": 1.5,
    "sympa": 1.5,
    "sympathique": 1.5,
    "professionnel": 2.0,
    "rapide": 1.5,
    "merci": 1.5,
    "bravo": 2.5,
    "plaisir": 2.0,
    "impeccable": 3.0,
    "nickel": 2.0,
    "propre": 1.0,
    "clair": 1.0,
    "fluide": 1.5,
    "intuitif": 1.5,
    "complet": 1.0,
    "innovant": 1.5,
    "stable": 1.0,
    "sécurisé": 1.5,
    "rapide": 1.5,
    "gratuit": 1.0,
    "avantageux": 1.5,
    "rentable": 1.5,
    "prometteur": 1.5,
    "idéal": 3.0,
    "exceptionnel": 3.0,
    "brillant": 2.5,
    "réussite": 2.5,
    "succès": 2.5,
    "joie": 2.0,
    "bonheur": 2.5,
    "amical": 1.5,
    "chaleureux": 2.0,
    "accueillant": 2.0,
    "poli": 1.5,
    "courtois": 1.5,
    "serviable": 2.0,
    "disponible": 1.5,
    "réactif": 2.0,
    "compétent": 2.0,
    "sérieux": 2.0,
    "confiance": 2.0,

    # NEGATIVE (-1.0 to -4.0)
    "horrible": -3.5,
    "terrible": -3.5,
    "affreux": -3.0,
    "épouvantable": -3.0,
    "catastrophique": -3.5,
    "scandaleux": -3.0,
    "inadmissible": -3.0,
    "inacceptable": -3.0,
    "honteux": -3.0,
    "nul": -2.5,
    "zéro": -2.5,
    "mauvais": -2.0,
    "médiocre": -2.5,
    "décevant": -2.0,
    "déception": -2.5,
    "frustrant": -2.0,
    "ennuyeux": -1.5,
    "difficile": -1.5,
    "compliqué": -1.5,
    "lent": -2.0,
    "cher": -1.5,
    "onéreux": -1.0,
    "excessif": -1.5,
    "déçu": -2.5,
    "mécontent": -2.5,
    "fâché": -2.0,
    "énervé": -2.0,
    "triste": -1.5,
    "problème": -1.5,
    "erreur": -1.5,
    "bug": -2.0,
    "panne": -2.5,
    "cassé": -2.5,
    "abîmé": -2.0,
    "défaillant": -2.0,
    "défectueux": -2.5,
    "inutile": -2.0,
    "perte": -2.0,
    "gâchis": -2.5,
    "arnaque": -3.5,
    "vol": -3.0,
    "voleur": -3.5,
    "escroquerie": -3.5,
    "mensonge": -3.0,
    "menteur": -3.0,
    "faux": -2.0,
    "dangereux": -2.5,
    "nocif": -2.5,
    "toxique": -2.5,
    "sale": -2.0,
    "dégoûtant": -3.0,
    "bruit": -1.0,
    "bruyant": -1.5,
    "froid": -1.0,
    "désagréable": -2.0,
    "impoli": -2.0,
    "irrespectueux": -2.5,
    "incompétent": -2.5,
    "amateur": -1.5,
    "lent": -1.5,
    "retard": -1.5,
    "attente": -1.0,
    "ignorer": -1.5,
    "refus": -1.5,
    "pire": -3.0,
    "méchant": -2.0,
    "agressif": -2.0,
    "stupide": -2.0,
    "idiot": -2.0,
    "bête": -1.5,
    "ridicule": -2.0,
    "pathétique": -2.5,
    "regrette": -2.0,
    "déconseille": -2.5,
    "fuir": -3.0,
    "évitez": -2.5,
}

# Negation words (invert sentiment)
NEGATIONS = {
    "ne", "n'", "pas", "plus", "jamais", "rien", "aucun", "aucune",
    "personne", "ni", "guère", "point", "sans"
}

# Booster words (intensify or diminish sentiment)
# Value is a multiplier or adder
BOOSTERS = {
    # Amplifiers (increase intensity)
    "très": 1.5,
    "trop": 1.3,
    "tellement": 1.4,
    "si": 1.3,
    "super": 1.5,
    "hyper": 1.5,
    "ultra": 1.5,
    "méga": 1.5,
    "extrêmement": 2.0,
    "incroyablement": 2.0,
    "vraiment": 1.5,
    "totalement": 1.5,
    "complètement": 1.5,
    "absolument": 1.5,
    "parfaitement": 1.5,
    "entièrement": 1.4,
    "grandement": 1.4,
    "fortement": 1.4,
    "terriblement": 1.4,
    "infiniment": 1.5,
    "sacrément": 1.4,
    "vachement": 1.4,
    "beaucoup": 1.3,
    "énormément": 1.5,
    "tout": 1.2,
    "plein": 1.2,
    
    # Attenuators (decrease intensity)
    "peu": 0.5,
    "un peu": 0.6,
    "presque": 0.8,
    "quasi": 0.8,
    "légèrement": 0.7,
    "à peine": 0.6,
    "plutôt": 0.9,
    "assez": 0.8,
    "moyennement": 0.7,
    "relativement": 0.9,
    "moins": 0.5,
}

# Expressions/idiomes
IDIOMS = {
    "ne marche pas": -2.0,
    "ne fonctionne pas": -2.0,
    "pas mal": 1.5,
    "pas terrible": -1.5,
    "pas du tout": -0.5,
    "rien à dire": 1.0,
    "rien a dire": 1.0,
    "top du top": 3.0,
    "hors de prix": -2.5,
    "bon rapport qualité prix": 2.5,
    "rapport qualité prix": 1.5,
    "perte de temps": -2.5,
    "foutage de gueule": -3.5,
    "laisse à désirer": -2.0,
    "plus jamais": -3.0,
    "à fuir": -3.0,
    "vaut le coup": 2.0,
    "vaut la peine": 2.0,
    "yeux fermés": 2.5, # "acheter les yeux fermés"
    "bonne affaire": 2.5,
    "mauvaise affaire": -2.5,
    "belle surprise": 2.5,
    "mauvaise surprise": -2.5,
}

# Quelques mots niches rajoutés suite à des tests sur d'autres corpus d'avis client
FRENCH_LEXICON.update({
    "star": 1.0,
    "stars": 1.0,
    "étoile": 1.0,
    "étoiles": 1.0,
    "mal": -1.5,
    "mauvaise": -2.0,
    "mauvaises": -2.0,
    "bons": 1.5,
    "bonnes": 1.5,
    "incompréhensible": -2.5,
    "pire": -3.0,
    "surprise": 1.0,
    "affaire": 0.5,
    "endommagé": -2.0,
    "dommage": -1.5,
    # Restauration
    "délicieux": 2.5,
    "régal": 2.5,
    "bruyante": -1.5,
    "bruyant": -1.5,
    "insipide": -2.0,
    "insipides": -2.0,
    "désagréable": -2.0,
    "excessif": -1.5,
    "excessifs": -1.5,
    "frais": 1.5,
    "brûlée": -2.0,
    "brûlé": -2.0,
    "cuite": 0.5,
    "douteuse": -2.0,
    "douteux": -2.0,
    "varié": 1.5,
    "équilibré": 1.5,
    "chaleureux": 2.0,
    "impeccable": 2.5,
    "décevante": -2.0,
    "décevant": -2.0,
    # Mode et Vêtements
    "magnifique": 2.5,
    "confortable": 2.0,
    "gratte": -1.5,
    "transparent": -1.0,
    "petit": -1.0,
    "grand": -1.0,
    "trou": -2.5,
    "inacceptable": -2.5,
    "erroné": -1.5,
    "fragile": -1.5,
    "fragiles": -1.5,
    "craqué": -2.0,
    "original": 1.5,
    "compliqué": -1.5,
    "agréable": 2.0,
    "respirante": 1.5,
    "bizarre": -1.0,
    "mal": -1.5,
    "bâclée": -2.0,
    "bâclées": -2.0,
    "maintien": 1.5,
    "ravie": 2.5,
    "ravi": 2.5,
})
